server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/heima
    username:
    password:
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka